# Generated by Django 3.1.5 on 2021-03-11 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tv_show',
            name='description',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='tv_show',
            name='release_date',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
    ]
